# Docker Compose file -- defines how to run the project's containers

services:
  # The Django web application
  web:
    # Build the image using the Dockerfile in the current directory (./Dockerfile)
    build: .
    init: true

    # Map port 8000 on your machine to port 8000 in the container
    ports:
      - "8000:8000"

    # Mount the current directory into /app in the container
    volumes:
      - .:/app

    # Configuración para Linux para que host.docker.internal funcione
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Environment variables for the container
    environment:
      - REDIS_HOST=redis
      - GAME_SERVER_API_URL=http://host.docker.internal:5000/partida-aleatoria

    depends_on:
      - redis

  # Redis for matchmaking
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
