# Generated by Django 6.0.3 on 2026-04-18 16:47

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[^@]+@gmail\\.com$')])),
                ('user_image', models.ImageField(blank=True, upload_to='user_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_iso', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{2}$')])),
                ('country_name', models.CharField(max_length=50)),
                ('flag_image', models.ImageField(blank=True, upload_to='country_flags/')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20)),
                ('dimensions', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('winner_name', models.CharField(max_length=50)),
                ('score_display', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d+-\\d+$')])),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)])),
            ],
        ),
        migrations.CreateModel(
            name='CounterUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='corresponding_CS_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('losses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kills', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('deaths', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('favourite_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.map')),
            ],
        ),
        migrations.AddField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_users', to='web.country'),
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('match_stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('kills', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('deaths', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.match')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.counteruser')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches_played', through='web.MatchStats', to='web.counteruser'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='web.counteruser'),
        ),
        migrations.CreateModel(
            name='LocalRanking',
            fields=[
                ('local_ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_country_counter_users', to='web.country')),
                ('counter_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_local_ranking', to='web.counteruser')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalRanking',
            fields=[
                ('global_ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('global_position', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_country_counter_users', to='web.country')),
                ('counter_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_global_ranking', to='web.counteruser')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'reviewee'), name='unique_reviewer_reviewee'), models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewee')), _negated=True), name='check_no_self_reviews')],
            },
        ),
        migrations.AddConstraint(
            model_name='matchstats',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'match'), name='unique_user_match'),
        ),
        migrations.AddConstraint(
            model_name='localranking',
            constraint=models.UniqueConstraint(fields=('country', 'local_position'), name='unique_country_ranking'),
        ),
    ]
