# Generated by Django 6.0.3 on 2026-04-11 18:12

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20)),
                ('dimensions', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('winner_name', models.CharField(max_length=50)),
                ('score_display', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d+-\\d+$')])),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)])),
            ],
        ),
        migrations.CreateModel(
            name='CounterUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='corresponding_CS_user', serialize=False, to='web.webuser')),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('losses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kills', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('deaths', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('favourite_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.map')),
            ],
        ),
        migrations.AddField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_users', to='web.country'),
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('match_stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('kills', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('deaths', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.match')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.counteruser')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches_played', through='web.MatchStats', to='web.counteruser'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='web.counteruser'),
        ),
        migrations.CreateModel(
            name='LocalRanking',
            fields=[
                ('local_ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_country_counter_users', to='web.country')),
                ('counter_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_local_ranking', to='web.counteruser')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalRanking',
            fields=[
                ('global_ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('global_position', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_country_counter_users', to='web.country')),
                ('counter_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_global_ranking', to='web.counteruser')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='web.webuser')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to='web.webuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'reviewee'), name='unique_reviewer_reviewee'), models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewee')), _negated=True), name='check_no_self_reviews')],
            },
        ),
        migrations.AddConstraint(
            model_name='matchstats',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'match'), name='unique_user_match'),
        ),
        migrations.AddConstraint(
            model_name='localranking',
            constraint=models.UniqueConstraint(fields=('country', 'local_position'), name='unique_country_ranking'),
        ),
    ]
