# Generated by Django 6.0.3 on 2026-04-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_users', to='web.country'),
        ),
    ]
