# Generated by Django 6.0.3 on 2026-04-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_webuser_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_users', to='web.country'),
        ),
    ]
