# Generated by Django 6.0.3 on 2026-04-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_webuser_user_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchstats',
            options={'verbose_name_plural': 'MatchStats'},
        ),
    ]
