# Generated by Django 6.0.3 on 2026-04-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_country_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webuser',
            options={'verbose_name': 'WebUser', 'verbose_name_plural': 'WebUsers'},
        ),
        migrations.AlterField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='country_users', to='web.country'),
        ),
    ]
