# Generated by Django 6.0.3 on 2026-04-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_webuser_options_alter_webuser_user_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counteruser',
            options={'verbose_name': 'CounterUser', 'verbose_name_plural': 'CounterUsers'},
        ),
    ]
