# Generated by Django 6.0.3 on 2026-04-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_counteruser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalranking',
            name='country',
        ),
    ]
