# Generated by Django 6.0.3 on 2026-04-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_globalranking_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalranking',
            options={'verbose_name': 'GlobalRanking', 'verbose_name_plural': 'GlobalRankings'},
        ),
        migrations.AlterModelOptions(
            name='localranking',
            options={'verbose_name': 'LocalRanking', 'verbose_name_plural': 'LocalRankings'},
        ),
    ]
