# Generated by Django 6.0.3 on 2026-04-19 14:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_globalranking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_lost', to='web.counteruser'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)]),
        ),
    ]
