# Generated by Django 6.0.3 on 2026-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_match_players_match_loser_match_loser_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('winner', models.F('loser')), _negated=True), name='winner_cannot_be_loser'),
        ),
    ]
