# Generated by Django 6.0.3 on 2026-05-10 11:22

import django.db.models.deletion
from django.db import migrations, models

from web.models import DEFAULT_COUNTRY


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_match_winner_cannot_be_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalranking',
            name='country',
            field=models.ForeignKey(default=DEFAULT_COUNTRY, on_delete=django.db.models.deletion.PROTECT, related_name='global_country_counter_users', to='web.country'),
            preserve_default=False,
        ),
    ]
