# Generated by Django 6.0.3 on 2026-05-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_globalranking_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='type',
            field=models.CharField(choices=[('Small', 'Small'), ('Big', 'Big')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_match_stats', to='web.match'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, related_name='country_users', to='web.country'),
        ),
    ]
