# Generated by Django 6.0.3 on 2026-05-16 10:07

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_country_country_name_alter_map_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counteruser',
            name='favourite_map',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.map'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_display',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^(10-[0-9]|[0-9]-10)$')]),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.PROTECT, related_name='country_users', to='web.country'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
