# Generated by Django 6.0.3 on 2026-05-17 06:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_matchstats_points_alter_counteruser_favourite_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalranking',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_country_counter_users', to='web.country'),
        ),
        migrations.AlterField(
            model_name='localranking',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_country_counter_users', to='web.country'),
        ),
        migrations.AlterField(
            model_name='map',
            name='type',
            field=models.CharField(choices=[('Small', 'Small'), ('Big', 'Big')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='deaths',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='kills',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_match_stats', to='web.match'),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_match_stats', to='web.counteruser'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_users', to='web.country'),
        ),
    ]
