# Generated by Django 6.0.3 on 2026-05-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_globalranking_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='log_file',
            field=models.FileField(blank=True, null=True, upload_to='match_logs/'),
        ),
    ]
