# Generated by Django 6.0.3 on 2026-05-17 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_match_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalranking',
            name='global_position',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='localranking',
            name='local_position',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
