# Generated by Django 6.0.5 on 2026-05-17 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_globalranking_global_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalranking',
            name='global_position',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='localranking',
            name='local_position',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
