# Generated by Django 6.0.5 on 2026-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_globalranking_global_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='log_file',
            field=models.FileField(null=True, upload_to='match_logs/'),
        ),
    ]
