# Generated by Django 6.0.5 on 2026-06-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_match_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalranking',
            name='country',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='global_country_counter_users', to='web.country'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='country_users', to='web.country'),
        ),
    ]
