# Generated by Django 6.0.5 on 2026-06-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_match_log_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='map_name',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='map_played',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_matches', to='web.map'),
        ),
        migrations.AddField(
            model_name='review',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='globalranking',
            name='country',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='global_country_counter_users', to='web.country'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='user_country',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='country_users', to='web.country'),
        ),
    ]
