# Generated by Django 6.0.5 on 2026-06-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_globalranking_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='map_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='map_played',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_matches', to='web.map'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
