# Generated by Django 6.0.5 on 2026-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_match_map_name_match_map_played_alter_map_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
